### ISSUE TITLE
Percentage format inconsistent by documentation

### ISSUE THREAD

**Issue by webjoel** [adamwdraper/Numeral-js#188]
Documentation for percentage format "pt-br":

0.974878234 > '0.000%' > 97,488%

is inconsistent, see:

...
var numeral = require('numeral');
...

numeral.language('pt-br', {
    delimiters: {
        thousands: '.',
        decimal: ','
    },
    abbreviations: {
        thousand: 'mil',
        million: 'milhões',
        billion: 'b',
        trillion: 't'
    },
    ordinal: function (number) {
        return 'º';
    },
    currency: {
        symbol: 'R$'
    }
});

numeral.language('pt-br');

...
console.log(numeral(9.090909090909092).format('0.00%')) // 909,09% // NOT OK
console.log(numeral(9.090909090909092).format('0.00') + %) // 9,09% // OK
...

**Comment by adamwdraper** [comment]
fixed

**Comment by brendonmm** [comment]
I didn't understand why you closed this issue, since there hasn't been resolved. 

I'm using release "2.0.4" and still multiplying by 100 the inserted value.

_console.log:_ 
numeral(1.0).format('0.00%') // 100,00% **--wrong**
numeral(1,0).format('0.00%') // 100,00% **--wrong**

numeral(1,0).format('0.00') + %) // 1,00% **--right**

**Comment by cod3rkane** [comment]
I'm using release "2.0.6" and still the same error with percentage.
