### ISSUE TITLE
Breaks when compiled with babel/es6

### ISSUE THREAD

**Issue by benoneal** [adamwdraper/Numeral-js#276]
Throws this error when attempting to compile with babel: 

```
[PROJECT_PATH]/node_modules/numeral/numeral.js:671
        this['numeral'] = numeral;
                        ^
TypeError: Cannot set property 'numeral' of undefined
```

Our workaround is to exclude this module explicitly in the babel config, but that's kinda crappy. 
(we are parsing our node_modules through babel because we use a bunch of es6 and react jsx modules)

**Comment by jamiter** [comment]
Hi, this repository is no longer maintained. You can get an improved version here: https://github.com/foretagsplatsen/numbro. That one is still maintained and you can report your issues there.

**Comment by adamwdraper** [comment]
i believe this is now fixed

**Comment by nahumzs** [comment]
~I'm still seeing this error in `^2.0.6` using webpack~ found out, it's because two libraries are importing `numeraljs` and have different versions.
